font:
  normal:
    family: Iosevka Term SS05 Extended 
    style: Regular

  bold:
    family: Iosevka Term SS05 Extended 
    style: Bold

  italic:
    family: Iosevka Term SS05 Extended 
    style: Italic

  bold_italic:
    family: Iosevka Term SS05 Extended 
    style: Bold Italic

  size: 8


hints:
  alphabet: "jfkdlsahgurieowpq"

  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: true
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift

colors:
  primary:
    background: '#000000'
    foreground: '#c5c8c6'

  cursor:
    text: '#aaaaaa'
    cursor: '#aa0033'
