#! /bin/bash

SAVEDIR=~/dat/read-later
USERAGENT='Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.6) Gecko/20070802 SeaMonkey/1.1.4'

mkdir -p "$SAVEDIR"

wget -U "$USERAGENT" -p -k -P "$SAVEDIR" "${QUTE_URL}"
