#! /bin/sh
# --
# Custom xsession for laptop, load openbox with a number of gnome applets
# and also a ggtraybar using dmon...

cd $HOME

export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

export DBUS_SESSION_BUS_ADDRESS
export DBUS_SESSION_BUS_WINDOWID
export DBUS_SESSION_BUS_PID

eval `cat $HOME/.fehbg` &
dmon -1 ${HOME}/dev/ggtraybar/ggt 2>&1 >/dev/null
dmon -1 gnome-settings-daemon 2>&1 >/dev/null
dmon -1 gnome-screensaver 2>&1 >/dev/null
dmon -1 gnome-power-manager 2>&1 >/dev/null
dmon -1 bluetooth-applet 2>&1 >/dev/null
dmon -i 10 -1 conky 2>&1 >/dev/null
dmon -1 nm-applet 2>&1 >/dev/null
dropbox start 2>&1 >/dev/null
exec /usr/bin/openbox --replace 2>&1 >/dev/null

