#! /bin/zsh

declare -a _kns_namespaces=()

_kns () {
  local -a kns_commands
  for cmd in ${(k)_kns_cmd[@]} ; do
    kns_commands=( "${kns_commands[@]}" "${cmd}:${_kns_cmd[${cmd}]}" )
  done

  typeset -A opt_args
  local state

  _arguments \
    "1: :{_describe 'command' kns_commands}" \
    '*:: :->args'

  case ${words[1]} in
    activate | rm)
      if [[ "${words[2]}" ]]; then
        KNS_CONTEXT="${words[2]}"

        if [[ "${#_kns_namespaces[@]}" -eq 0 ]]; then
          _kns_namespaces=(
            $(kubectl get namespaces \
                -o go-template \
                --template '{{range .items}}{{.metadata.name}} {{end}}')
          )
        fi
        _arguments "2: :{_describe 'kns' _kns_namespaces}"
      else
        local -a kns_context=( $(kns ls) )
        _arguments "1: :{_describe 'kns' kns_context}"
      fi
      ;;
    new)
      if typeset -fz _kns ; then
        _arguments \
          '1:kns name:' \
          '*:kns args:_kns'
      else
        _arguments \
          '1:kns name:' \
          '*:kns args:'
      fi
      ;;
  esac
}

compdef _kns kns
