#! /bin/bash

SYS_MAIL_DIR=~/sys/mail

count_unread_mails ()
{
  local -a unread=( $(notmuch search --output=files tag:unread) )
  echo "${#unread[@]}"
}

count="$(count_unread_mails)"
if [[ "$count" -gt 0 ]]; then
  echo "$count" > "${SYS_MAIL_DIR}/.new"
else
  rm -f "${SYS_MAIL_DIR}/.new"
fi
