#! /bin/bash

notmuch search --format json tag:new |
  jq -r '.[] | .authors + "|" + .subject' |
  (
    IFS='|'
    while read -r authors subject; do
      [[ ${#subject} -gt 20 ]] && subject="${subject:0:20}…"
      notify-send -u low  "  ${subject}" "    <i>$authors</i>"
    done
  )
