#! /bin/bash

notmuch new >/dev/null 2>&1

# tag by source
notmuch tag +cron      -- tag:new and from:@ajdiaz.me and from:cron
notmuch tag +alert     -- tag:new and from:alert@uptimerobot.com

# tag mailing lists
notmuch tag +list +devops-weekly -- tag:new and subject:"Devops Weekly #"
notmuch tag +list +arch-security -- to:"arch-security@archlinux.org"

# tag by source folder
notmuch tag +sent     -new -inbox -- tag:new and folder:ajdiaz.me/Sent
notmuch tag +deleted  -new -inbox -- tag:new and folder:ajdiaz.me/Trash
notmuch tag +flagged  -new -inbox -- tag:new and folder:ajdiaz.me/Flagged
notmuch tag +spam     -new -inbox -- tag:new and folder:ajdiaz.me/Junk
notmuch tag +archive  -new -inbox -- tag:new and folder:ajdiaz.me/Archive
notmuch tag +drafts   -new -inbox -- tag:new and folder:ajdiaz.me/Drafts

# untag new if already in inbox
notmuch tag -new -- tag:inbox

# tag inbox
notmuch tag +inbox +unread -- tag:new
