#! /bin/bash

warn=30
crit=15
command="sudo systemctl suspend"

batt="BAT0"
full="$(</sys/class/power_supply/${batt}/charge_full)"
curr="$(</sys/class/power_supply/${batt}/charge_now)"
percent="$((curr*100/full))"
state="$(</sys/class/power_supply/${batt}/status)"

case "$state" in
  Discharging)
    if [ $percent -lt $crit ]; then
      notify-send -u critical "${message_title}"
      i3-nagbar -m "  Battery is critical and the system will be suspended." \
        -t error -f 'pango:DejaVu Sans Mono 6'
      sleep 5
      $command
    elif [ $percent -lt $warn ]; then
      if [ ! -r ~/.cache/batt-notify ]; then
        i3-nagbar -m "  Battery level is lower than ${warn}%." \
                  -t warning -f 'pango:DejaVu Sans Mono 6'
        xbacklight -time 500 -steps 30 -set 5
        touch ~/.cache/batt-notify
      fi
    fi;;
    *)
    if [ -r ~/.cache/batt-notify ]; then
      rm -f ~/.cache/batt-notify
    fi;;
esac
