#! /bin/bash

warn=30
crit=15
command="sudo systemctl suspend"

batt="BAT0"
full="$(</sys/class/power_supply/${batt}/charge_full)"
curr="$(</sys/class/power_supply/${batt}/charge_now)"
percent="$((curr*100/full))"
state="$(</sys/class/power_supply/${batt}/status)"

case "$state" in
  Discharging)
    if [ $percent -lt $crit ]; then
      notify-send -u critical "   battery level critical" "suspending in 30s..."
      sleep 30
      state="$(</sys/class/power_supply/${batt}/status)"
      if [[ "$state" = "Discharging" ]]; then
        $command
      fi
    elif [ $percent -lt $warn ]; then
      if [ ! -r ~/.cache/batt-notify ]; then
        notify-send -u normal "   battery level low" "adjusting brithness..."
        xbacklight -time 500 -steps 30 -set 5
        touch ~/.cache/batt-notify
      fi
    fi;;
    *)
    if [ -r ~/.cache/batt-notify ]; then
      rm -f ~/.cache/batt-notify
    fi;;
esac
