#! /bin/bash

XRANDR="xrandr"
CMD="${XRANDR}"
declare -A VOUTS
eval VOUTS="$(${XRANDR}|awk 'BEGIN {printf("(")} /^\S.*connected/{printf("[%s]=%s ", $1, $2)} END{printf(")")}')"
declare -A POS
#XPOS=0
#YPOS=0
#POS="${XPOS}x${YPOS}"

POS=([X]=0 [Y]=0)

find_mode() {
  xrandr |
   awk -v monitor="^DP1 connected" '/connected/ {p = 0}
      $0 ~ monitor {p = 1}
      $0 !~ "connected" && p { print $1 }' | sort -n -r | head -n 1
}

xrandr_params_for() {
  if [ "${2}" == 'connected' ]
  then
    if [ "${1:0:3}" == 'DP1' ]; then
      eval "$(find_mode "${1}")"  #sets ${WIDTH} and ${HEIGHT}
      MODE="$(find_mode "$1")"
      local scale="--scale 2x2 --mode ${MODE}"
      notify-send "  $1: ${MODE}" "Screen attached"
    elif [ "${1:0:3}" == "eDP" ]; then
      local scale="--scale 1x1 --auto"
      WIDTH="3840"
    fi
    CMD="${CMD} --output ${1}  ${scale} --pos ${POS[X]}x${POS[Y]}"
    POS[X]=$((POS[X]+${WIDTH%%x*}))
    return 0
  else
    CMD="${CMD} --output ${1} --off"
    return 1
  fi
}

for VOUT in ${!VOUTS[*]}
do
  xrandr_params_for "${VOUT}" "${VOUTS[${VOUT}]}"
done

${CMD}
